apiVersion: operator.openshift.io/v1alpha1
kind: SpireOIDCDiscoveryProvider
metadata:
  name: cluster
spec:
  logLevel: info
  logFormat: text
  jwtIssuer: "https://spire-oidc.apps.cluster-ngll2.dynamic2.redhatworkshops.io"
  csiDriverName: "csi.spiffe.io"
  replicaCount: 1
  managedRoute: "true"
