apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-service
  namespace: ztwim-simple
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: consumer
  namespace: ztwim-simple
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: consumer-unauthorized
  namespace: ztwim-simple
