FROM registry.access.redhat.com/ubi9/python-311:latest

RUN pip install --no-cache-dir 'PyJWT[crypto]'

COPY *.py /app/
COPY templates/ /app/templates/

WORKDIR /app

EXPOSE 8080

CMD ["python", "/app/consumer.py"]
