apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-service
  namespace: ztwim-oidc-simple
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oidc-consumer
  namespace: ztwim-oidc-simple
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oidc-consumer-unauth
  namespace: ztwim-oidc-simple
